// lib/utils/app_config.dart

import 'dart:io' show Platform;
import 'package:flutter/foundation.dart' show kIsWeb;

class AppConfig {
  static String get apiUrl {
    // Port generated by .NET: 53978 (HTTP)
    if (kIsWeb) return 'http://localhost:53978/api';
    
    try {
      if (Platform.isAndroid) {
        return 'http://10.0.2.2:53978/api';
      }
    } catch (_) {}
    
    return 'http://localhost:53978/api';
  }
}
